#!/bin/bash

# Remove dev and prod directories
cd ~ || exit
rm -rf msl-viewer
rm -rf map-stroke

# Clone dev and prod repo
git clone git@github.com:map-stroke/msl-viewer.git
git clone git@github.com:brunosag/map-stroke.git

# Remove all files inside prod directory (except /.git)
cd map-stroke/ || exit
shopt -s extglob dotglob
rm -rf !(.git)

# Copy all contents of dev directory into prod directory (except /.git)
cd ../msl-viewer/ || exit
git checkout origin/dev
rsync -a --exclude '.git/' ./ ../map-stroke/

# Get last commit message from dev repo
last_commit_message=$(git log -1 --pretty=%B)

# Commit and push changes to prod repo
cd ../map-stroke/ || exit
git add .
git commit -m "$last_commit_message"
git push origin main

# Remove directories
cd ~ || exit
rm -rf msl-viewer
rm -rf map-stroke
