#!/bin/bash

# Remove dev and prod directories
cd ~ || exit
rm -rf hopa-dev
rm -rf hopa

# Clone dev and prod repo
git clone git@github.com:brunosag/hopa-dev.git
git clone git@github.com:sbcblab/hopa.git

# Remove all files inside prod directory (except /.git)
cd hopa-dev/ || exit
shopt -s extglob dotglob
rm -rf !(.git)

# Copy all contents of dev directory into prod directory (except /.git)
cd ../hopa/ || exit
rsync -a --exclude '.git/' ./ ../hopa-dev/

# Get last commit message from dev repo
last_commit_message=$(git log -1 --pretty=%B)

# Commit and push changes to prod repo
cd ../hopa-dev/ || exit
git add .
git commit -m "$last_commit_message"
git push origin main

# Remove directories
cd ~ || exit
rm -rf hopa
rm -rf hopa-dev
