#!/usr/bin/env bash

if [ $# -ne 1 ]; then
	echo "Usage: $0 <subtitles_file>"
	exit 1
fi

input_file="$1"

cp "$input_file" "$input_file.bak" # backup

# remove content within both fullwidth and regular parentheses
sed -i 's/([^)]*)//g; s/（[^）]*）//g' "$input_file"

echo "Parentheses removed. Original file backed up as $input_file.bak"
